56. WAQTD THE MAX SALARY AND MIN SALARY IN THE EMP TABLE.

SELECT MAX(SAL),MIN(SAL)
FROM EMP;

57. WAQTD THE TOTAL SALARY AND AVG SALARY OBTAINED FROM EMP TABLE.

SELECT SUM(SAL),AVG(SAL)
FROM EMP;

58. WAQTD THE MAX SALARY AND TOTAL SALARY GIVEN TO ALL THE SALESMAN.

SELECT MAX(SAL),SUM(SAL)
FROM EMP
WHERE JOB='SALESMAN';

59. WAQTD THE MIN SALARY GIVEN TO THE EMP WHOSE LNAME ENDS WITH Y OR I.

SELECT MIN(SAL)
FROM EMP
WHERE LNAME LIKE '%Y' OR LNAME LIKE '%I';

60. WAQTD THE MAX SALARY, MIN SALARY OBTAINED IF THE EMP IS WORKING AS SALESMAN, MANAGER OR DISPATCHER.

SELECT MAX(SAL),MIN(SAL)
FROM EMP
WHERE JOB IN ('SALESMAN','MANAGER','DISPATCHER');

61. WAQTD THE DOB OF ELDEST EMP FROM EMP TABLE.

SELECT MIN(DOB)
FROM EMP;

62. WAQTD THE DOJ OF RECENTLY JOINED EMP.

SELECT MAX(DOJ)
FROM EMP;
