178. WAQTD THE EMP FNAME, SAL, DNO IF THE EMP IS GETTING SALARY MORE THAN ALL THE EMP WHO ARE WORKING IN DEPT 112.

SELECT FNAME, SAL, DNO FROM EMP WHERE SAL>ALL
(SELECT SAL FROM EMP WHERE DNO=112);

179. WAQTD THE DETAILS OF EMP IF THE EMP IS GETTING SALARY MORE THAN ANY OF THE DISPATCHER.

SELECT * FROM EMP WHERE SAL>ANY
(SELECT SAL FROM EMP WHERE JOB='DISPATCHER');

180. WAQTD THE EMP FNAME, SAL IF THE EMP IS NOT WORKING AS CEO BUT GETTING SALARY MORE THAN ANY OF THE EMPS WHOSE FNAME START WITH VOWELS.

SELECT FNAME, SAL FROM EMP WHERE JOB!='CEO' AND SAL>ANY
(SELECT SAL FROM EMP WHERE LEFT(FNAME,1)IN('A','E','I','O','U'));

181. WAQTD THE EMP FULLNAME WHO IS NOT A REPORTING MANAGER / WHERE NO EMPS ARE REPORTING TO HIM.
(If a emp is not a reporting manager, his eid must not be present in MGR column).

SELECT CONCAT(FNAME,' ',LNAME) FULLNAME FROM EMP WHERE EID NOT IN
(SELECT MGR FROM EMP WHERE MGR IS NOT NULL);

182. WAQTD THE DETAILS OF PRODUCTS DELIVERED IN THE MONTH OF MAY.

SELECT * FROM PRODUCT WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM ORDERS WHERE MONTH(DELIVERY_DATE)=5);

183. WAQTD THE DETAILS OF CUSTOMER WHO HAVE NEVER ORDERED ANY PRODUCT SO FAR.

SELECT * FROM CUSTOMER WHERE CID NOT IN
(SELECT CID FROM ORDERS);

184. WAQTD THE DETAILS OF LOCATION WHERE NO DEPTS ARE LOCATED.

SELECT * FROM LOCATION WHERE LID NOT IN
(SELECT LID FROM DEPT);

185. WAQTD THE DETAILS OF EMP IF THE EMP IS GETTING SAL MORE THAN AVG SALARY OF DEPT 112.

SELECT * FROM EMP WHERE SAL>
(SELECT AVG(SAL) FROM EMP WHERE DNO=112);

186. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY LESS THAN THE AVERAGE SALARY OF ALL EMPLOYEES.
SELECT * FROM EMP
WHERE SAL <
(SELECT AVG(SAL) FROM EMP);

187. WAQTD THE EMP FNAME, SAL WHO ARE GETTING THE MAXIMUM SALARY.
SELECT FNAME, SAL FROM EMP
WHERE SAL =
(SELECT MAX(SAL) FROM EMP);

188. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY MORE THAN THE MINIMUM SALARY OF DEPT 112.
SELECT * FROM EMP
WHERE SAL >
(SELECT MIN(SAL) FROM EMP WHERE DNO=112);

189. WAQTD THE EMP FNAME, SAL, DNO WHO ARE GETTING SALARY LESS THAN ALL THE EMPLOYEES WORKING IN DEPT 112.
SELECT FNAME, SAL, DNO FROM EMP
WHERE SAL < ALL
(SELECT SAL FROM EMP WHERE DNO=112);




