1. WAQTD THE EMP FNAME, LNAME, SAL AND ANNUAL SAL FROM EMP TABLE.

SELECT FNAME,LNAME,SAL,SAL*12
FROM EMP;

2. WAQTD THE EMP FNAME, LNAME, SAL, ANNUAL WITH 50000 BONUS.

SELECT FNAME,LNAME,SAL,SAL*12+50000
FROM EMP;

3. WAQTD THE EMP FNAME,SAL WITH 4000 INCENTIVE.

SELECT FNAME,SAL+4000
FROM EMP;

4. WAQTD THE EMP FNAME, SAL WITH 5% INCENTIVE.

SELECT FNAME,SAL+SAL*0.05
FROM EMP;

5. WAQTD THE EMP FNAME, SAL WITH 3000 DEDUCTION.

SELECT FNAME,SAL-3000
FROM EMP;

6. WAQTD THE EMP FNAME, SAL WITH 4% DEDUCTION.

SELECT FNAME,SAL-SAL*0.04
FROM EMP;

7. WAQTD THE DETAILS OF THE EMP.

SELECT *
FROM EMP;

8. WAQTD THE DETAILS ALONG WITH ANNUAL SAL FROM EMP TABLE.

SELECT *,SAL*12
FROM EMP;

9. WAQTD THE EMP FNAME,SAL WITH 4% HIKE AND COMM WITH 3% DEDUCTION.

SELECT FNAME,SAL+SAL*0.04 "SAL WITH 4% HIKE",
COMM-COMM*0.03 "COMM WITH 3% DEDUCTION"
FROM EMP;

10. waqtd the emp fname,SAL
select fname,sal 
from emp;

11.WAQTD THE DETAILS OF EMP
SELECT * 
FROM EMP;

12.WAQTD THE FNAME,SAL FROM EMP
SELECT FNAME,SAL FROM EMP;

13.WAQTD TO DISPLAY FNAME+LNAME AS RAJSHEKAR REDDY
SELECT CONCAT(FNAME,LNAME) FROM EMP;
