112. WAQTD THE FULL NAME OF THE EMPS.

FULLNAME
--------

SELECT CONCAT(FNAME,' ',LNAME) FULLNAME
FROM EMP;

113. WAQTD THE FNAME, LENGTH OF FNAME FROM THE GIVEN TABLE.

SELECT FNAME,LENGTH(FNAME)
FROM EMP;

114. WAQTD THE FNAME, JOB ROLE IN THE BELOW FORMAT.

SELECT CONCAT(FNAME,' - ',JOB) EMP_INFO
FROM EMP;

EMP_INFO
=========
Siddarth - CEO

===========================================================================
115. WAQTD THE FNAME, FIRST 3 CHARACTERS OF THE FNAME.

SELECT FNAME,SUBSTR(FNAME,1,3)
FROM EMP;

116. WAQTD THE LAST 2 CHARACTERS OF LNAME.

SELECT SUBSTR(LNAME,-2)
FROM EMP;

117. WAQTD THE DETAILS OF EMP IF THE EMP FNAME STARTS WITH S WITHOUT USING LIKE OPERATOR.

SELECT *
FROM EMP
WHERE SUBSTR(FNAME,1,1)='S';

118. WAQTD THE FNAME OF EMP IF THE EMP FNAME STARTS WITH VOWELS.

SELECT FNAME
FROM EMP
WHERE SUBSTR(FNAME,1,1)IN('A','E','I','O','U');

119. WAQTD THE DETAILS OF EMP IF THE EMP LNAME ENDS WITH Y OR I.

SELECT *
FROM EMP
WHERE SUBSTR(LNAME,-1)IN('Y','I');

120. WAQTD THE DETAILS OF EMP IF THE LNAME DOESNOT END WITH VOWELS.

SELECT *
FROM EMP
WHERE SUBSTR(LNAME,-1) NOT IN ('A','E','I','O','U');

121. WAQTD THE FIRST HALF OF THE FNAME.

Siddarth -> Sidd

SELECT SUBSTR(FNAME,1,LENGTH(FNAME)/2)
FROM EMP;

122. WAQTD THE SECOND HALF OF THE FNAME.

Siddarth -> arth

SELECT SUBSTR(FNAME,LENGTH(FNAME)/2+1)
FROM EMP;

123. WAQTD THE FNAME, FIRST HALF Of FNAME IN LOWER AND SECOND HALF OF THE FNAME IN UPPER REVERSE CASE.

SELECT FNAME,CONCAT(
LOWER(SUBSTR(FNAME,1,LENGTH(FNAME)/2)),
REVERSE(UPPER(SUBSTR(FNAME,LENGTH(FNAME)/2+1)))) TRAVERSED_NAME
FROM EMP;

124. WAQTD THE FNAME, LAST 3 CHARACTERS OF THE FNAME IN UPPERCASE.
SELECT FNAME,
UPPER(SUBSTR(FNAME,-3)) AS LAST3
FROM EMP;

125. WAQTD THE FNAME, REPLACE ALL OCCURRENCES OF 'A' WITH '@'.
SELECT FNAME,
REPLACE(FNAME,'A','@') AS MODIFIED_NAME
FROM EMP;

126. WAQTD THE FNAME, CONVERT THE FNAME INTO UPPERCASE.

SELECT FNAME,
UPPER(FNAME) AS UPPER_NAME
FROM EMP;

127. WAQTD THE FNAME, REVERSE OF THE FNAME.

SELECT FNAME, REVERSE(FNAME) AS REVERSED_NAME
FROM EMP;


