186. WAQTD THE DETAILS OF EMP IF THE EMP IS GETTING SAL MORE THAN AVG SALARY OF HIS DEPT.

SELECT * FROM EMP E1 WHERE SAL>
(SELECT AVG(SAL) FROM EMP WHERE DNO=E1.DNO);

187. WAQTD THE DETAILS OF AMAN'S MANAGER.

SELECT * FROM EMP WHERE EID IN
(SELECT MGR FROM EMP WHERE FNAME='AMAN');

188. WAQTD THE DETAILS OF EMP IF THE EMP IS ELFER THAN KIRAN'S MANAGER.

SELECT * FROM EMP WHERE DOB<
(SELECT DOB FROM EMP WHERE EID IN
(SELECT MGR FROM EMP WHERE FNAME='KIRAN'));

189. WAQTD THE DETAILS OF EMP IF THE EMP IS ELDER THAN THEIR REPORTING MANAGER.

SELECT * FROM EMP E1 WHERE DOB<
(SELECT DOB FROM EMP WHERE EID=E1.MGR);

190. WAQTD THE DETAILS OF EMP IF THE EMP AND HIS REPORTING MANAGER ARE SAME GENDER.

SELECT * FROM EMP E1 WHERE GENDER IN
(SELECT GENDER FROM EMP WHERE EID=E1.MGR);

191. WAQTD THE DETAILS OF EMP IF THE EMP IS REPORTING TO SAMEER.

SELECT * FROM EMP WHERE MGR IN
(SELECT EID FROM EMP WHERE FNAME='SAMEER');

192. WAQTD THE DETAILS OF PRODUCT IF THE PRODUCT HAS BEEN ORDERED EXACTLY TWICE.

SELECT * FROM PRODUCT WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM ORDERS
GROUP BY PRODUCT_ID HAVING COUNT(*)=2);

193. WAQTD THE DETAILS OF CUSTOMER WHO HAVE ORDERED MORE THAN ONCE.

SELECT * FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS GROUP BY CID HAVING COUNT(*)>1);

194. WAQTD THE DETAILS OF TOP 3 MOST SELLING PRODUCT.
{Based on number of items sold}

SELECT * FROM PRODUCT WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM 
(SELECT PRODUCT_ID
FROM ORDERS
GROUP BY PRODUCT_ID
ORDER BY COUNT(*) DESC
LIMIT 3) RESULT_TABLE);

195. WAQTD THE DETAILS OF EMP WHO IS GETTING THE HIGHEST SALARY IN HIS DEPARTMENT.

SELECT * FROM EMP E1
WHERE SAL =
(
    SELECT MAX(SAL)
    FROM EMP
    WHERE DNO = E1.DNO
);

196. WAQTD THE DETAILS OF CUSTOMER WHO HAS ORDERED THE MOST PRODUCTS.

SELECT * FROM CUSTOMER
WHERE CID IN
(
    SELECT CID
    FROM
    (
        SELECT CID
        FROM ORDERS
        GROUP BY CID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) RESULT_TABLE
);

197. WAQTD THE DETAILS OF EMP WHO IS GETTING THE LOWEST SALARY IN HIS DEPARTMENT.

SELECT * FROM EMP E1
WHERE SAL =
(
    SELECT MIN(SAL)
    FROM EMP
    WHERE DNO = E1.DNO
);

198. WAQTD THE DETAILS OF EMP WHO IS GETTING MORE SALARY THAN HIS MANAGER.

SELECT * FROM EMP E1
WHERE SAL >
(
    SELECT SAL
    FROM EMP
    WHERE EID = E1.MGR
);

199. WAQTD THE DETAILS OF EMP WHO IS JOINED BEFORE HIS MANAGER.

SELECT * FROM EMP E1
WHERE DOJ <
(
    SELECT DOJ
    FROM EMP
    WHERE EID = E1.MGR
);

200. WAQTD THE DETAILS OF EMP WHO IS GETTING MORE SALARY THAN THE AVERAGE SALARY OF HIS DEPARTMENT.

SELECT * FROM EMP E1
WHERE SAL >
(
    SELECT AVG(SAL)
    FROM EMP
    WHERE DNO = E1.DNO
);

201. WAQTD THE DETAILS OF EMP WHO IS JOINED AFTER HIS MANAGER.

SELECT * FROM EMP E1
WHERE DOJ >
(
    SELECT DOJ
    FROM EMP
    WHERE EID = E1.MGR
);



