69. WAQTD THE NUMBER OF EMPS WORKING IN EACH DEPT.

SELECT COUNT(*),DNO
FROM EMP
GROUP BY DNO;

70. WAQTD THE MAXIMUM SALARY GIVEN IN EACH DEPT.

SELECT MAX(SAL),DNO
FROM EMP
GROUP BY DNO;

71. WAQTD THE NUMBER OF EMPS AND MAX SALARY GIVEN IN EVERY JOB ROLE.

SELECT COUNT(*),MAX(SAL),JOB
FROM EMP
GROUP BY JOB;

72. WAQTD THE NUMBER OF EMPS WORKING IN EVERY DEPT IF THE EMP GETTING SALARY MORE THAN 34000.

SELECT COUNT(*),DNO
FROM EMP
WHERE SAL>34000
GROUP BY DNO;

73. WAQTD THE MAX SALARY, MIN SALARY, AVG SALARY GIVEN IN EVERY DEPT.

SELECT MAX(SAL),MIN(SAL),AVG(SAL),DNO
FROM EMP
GROUP BY DNO;

74. WAQTD THE NUMBER OF EMPS REPORTING TO EVERY MANAGER(MGR).

SELECT COUNT(*),MGR
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

75. WAQTD THE NUMBER OF EMPS WHO ARE GETTING SALARY MORE THAN OR EQUAL TO 32000 AND SALARY LESS THAN OR EQUAL TO 100000 IN EACH DEPT.

SELECT COUNT(*),DNO
FROM EMP
WHERE SAL BETWEEN 32000 AND 100000
GROUP BY DNO;

76. WAQTD THE MAX SALARY, MIN SALARY, AVG SALARY GIVEN IN EVERY DEPT.

SELECT MAX(SAL),MIN(SAL),AVG(SAL),DNO
FROM EMP
GROUP BY DNO;

77. WAQTD THE NUMBER OF EMPS REPORTING TO EVERY MANAGER(MGR).

SELECT COUNT(*),MGR
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

78. WAQTD THE TOTAL SALARY PAID TO EMPLOYEES IN EACH DEPT.

SELECT SUM(SAL), DNO
FROM EMP
GROUP BY DNO;

79. WAQTD THE AVERAGE SALARY OF EMPLOYEES IN EACH JOB ROLE.

SELECT AVG(SAL), JOB
FROM EMP
GROUP BY JOB;

80. WAQTD THE NUMBER OF EMPS WORKING IN EACH JOB ROLE.

SELECT COUNT(*), JOB
FROM EMP
GROUP BY JOB;


