243. waqtd the dept name and number of emps working in that dept.

SELECT D.DNAME, COUNT(*)
FROM DEPT D INNER JOIN EMP E
ON D.DNO=E.DNO
GROUP BY D.DNO,D.DNAME;

SELECT D.DNAME,GROUP_CONCAT(E.FNAME)
FROM DEPT D INNER JOIN EMP E
ON D.DNO=E.DNO
GROUP BY D.DNO,D.DNAME;

244. WAQTD THE LCOATION NAMES AND LIST OF DEPTS LOCATED IN THAT LOCATION.

SELECT L.LOCATION, GROUP_CONCAT(D.DNAME)
FROM LOCATION L INNER JOIN DEPT D
ON L.LID=D.LID
GROUP BY L.LID, L.LOCATION;

246. WAQTD THE TOP 3 CUSTOMERS, TOTAL AMOUNT WHO HAVE SPENT THE MOST OVERALL.

SELECT SUM(P.PRICE),O.CID,COUNT(*)
FROM PRODUCT P INNER JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY O.CID
ORDER BY SUM(P.PRICE) DESC
LIMIT 3;

247. WAQTD THE TOP 3 STATES WITHE HIGHEST REVENUE.

SELECT L.STATE,SUM(P.PRICE) REVENUE
FROM PRODUCT P INNER JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID INNER JOIN CUSTOMER C
ON O.CID=C.CID INNER JOIN LOCATION L
ON C.LID=L.LID
GROUP BY L.STATE
ORDER BY REVENUE DESC
LIMIT 3;

248. WAQTD THE TOP 3 MONTHS WITH THE HIGHEST REVENUE.

SELECT DATE_FORMAT(O.ORDER_DATE,'%M') MONTH, SUM(P.PRICE) REVENUE
FROM ORDERS O INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID
GROUP BY MONTH
ORDER BY REVENUE DESC
LIMIT 3;

OR

WITH monthly_revenue AS
(
   SELECT DATE_FORMAT(O.ORDER_DATE,'%M') MONTH, SUM(P.PRICE) REVENUE
   FROM ORDERS O INNER JOIN PRODUCT P
   ON O.PRODUCT_ID=P.PRODUCT_ID
   GROUP BY MONTH
)
SELECT *
FROM MONTHLY_REVENUE
ORDER BY REVENUE DESC
LIMIT 3;

249. WAQTD THE EMP FULL NAME, WHO HAS DELIVERED MOST NUMBER OF ORDERS.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME, COUNT(*)
FROM EMP E INNER JOIN ORDERS O
ON E.EID=O.EID
GROUP BY FULLNAME
ORDER BY COUNT(*) DESC
LIMIT 1;

250. WAQTD THE EMP FULLNAME, DEPT NAME IF THE EMP IS WORKING IN DEPTS LOCATED IN BANGALORE.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME, D.DNAME
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO INNER JOIN LOCATION L
ON D.LID=L.LID 
WHERE L.CITY='BANGALORE';

====================================================================
251. WAQTD THE EMP FNAME, JOB IF THE EMP IS WORKING AS SALESMAN OR MANAGER.

SELECT FNAME, JOB
FROM EMP
WHERE JOB IN ('SALESMAN','MANAGER');

WITH emp_data AS
(
	SELECT FNAME, JOB
        FROM EMP
        WHERE JOB IN ('SALESMAN','MANAGER')
)
SELECT *
FROM EMP_DATA;

252. WAQTD THE CUSTOMER FNAME IF THE CUSTOMER FNAME STARTS WITH VOWELS.

WITH cust AS
(
SELECT FIRST_NAME
FROM CUSTOMER
WHERE LEFT(FIRST_NAME,1) IN ('A','E','I','O','U')
)
SELECT *
FROM CUST;

253. WAQTD THE EMP DETAILS ALONG WITH ANNUAL SALARY IF EMP IS GETTING ANNUAL SALARY MORE THAN 500000.

WITH annual_data AS
(
SELECT *, SAL*12 ANNUAL_SAL
FROM EMP)
SELECT *
FROM ANNUAL_DATA
WHERE ANNUAL_SAL>500000;

254. WAQTD THE EMP FNAME AND DEPT NAME BY USING COMMON TABLE EXPRESSION.

WITH emp_data AS
(
  SELECT FNAME,DNO
  FROM EMP
)
SELECT ED.FNAME, D.DNAME
FROM EMP_DATA ED INNER JOIN DEPT D
ON ED.DNO=D.DNO;

255. WAQTD THE EMP FULL NAME, WHO HAS DELIVERED MOST NUMBER OF ORDERS.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME, COUNT(*)
FROM EMP E INNER JOIN ORDERS O
ON E.EID=O.EID
GROUP BY FULLNAME
ORDER BY COUNT(*) DESC
LIMIT 1;


