243. waqtd the dept name and number of emps working in that dept.

SELECT D.DNAME, COUNT(*)
FROM DEPT D INNER JOIN EMP E
ON D.DNO=E.DNO
GROUP BY D.DNO,D.DNAME;

SELECT D.DNAME,GROUP_CONCAT(E.FNAME)
FROM DEPT D INNER JOIN EMP E
ON D.DNO=E.DNO
GROUP BY D.DNO,D.DNAME;

244. WAQTD THE LCOATION NAMES AND LIST OF DEPTS LOCATED IN THAT LOCATION.

SELECT L.LOCATION, GROUP_CONCAT(D.DNAME)
FROM LOCATION L INNER JOIN DEPT D
ON L.LID=D.LID
GROUP BY L.LID, L.LOCATION;

246. WAQTD THE TOP 3 CUSTOMERS, TOTAL AMOUNT WHO HAVE SPENT THE MOST OVERALL.

SELECT SUM(P.PRICE),O.CID,COUNT(*)
FROM PRODUCT P INNER JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY O.CID
ORDER BY SUM(P.PRICE) DESC
LIMIT 3;

247. WAQTD THE TOP 3 STATES WITHE HIGHEST REVENUE.

SELECT L.STATE,SUM(P.PRICE) REVENUE
FROM PRODUCT P INNER JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID INNER JOIN CUSTOMER C
ON O.CID=C.CID INNER JOIN LOCATION L
ON C.LID=L.LID
GROUP BY L.STATE
ORDER BY REVENUE DESC
LIMIT 3;

