77. WAQTD THE MAX SALARY, MIN SALARY GIVEN TO EACH DEPT IF THE DEPT MAX SALARY IS LESS THAN 200000.

SELECT MAX(SAL),MIN(SAL),DNO
FROM EMP
GROUP BY DNO
HAVING MAX(SAL)<200000;

78. WAQTD THE TOTAL SALARY GIVEN IN EVERY JOB ROLE IF THE JOB ROLE CONTAINS ATLEAST 3 EMPS WORKING IN IT.

SELECT SUM(SAL),JOB
FROM EMP
GROUP BY JOB
HAVING COUNT(*)>=3;

79. WAQTD THE NUMBER OF EMPS WORKING IN EACH DEPT IF THE DEPT MIN SAL IS MORE THAN 32000 AND MAX SALARY LESS THAN 200000.

SELECT COUNT(*),DNO
FROM EMP
GROUP BY DNO
HAVING MIN(SAL)>32000 AND MAX(SAL)<200000;

80. WAQTD THE MAX SALARY, MIN SALARY FROM EVERY DEPT IF THE AVG SALARY OF THE DEPT IS MORE THAN 40000.

SELECT MAX(SAL),MIN(SAL),DNO
FROM EMP
GROUP BY DNO
HAVING AVG(SAL)>40000;

81. WAQTD THE NUMBER OF EMPS WHO ARE GETTING SAME SALARY.

SELECT COUNT(*),SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(*)>1;

82. WAQTD THE NUMBER OF EMPS WHO ARE WORKING IN SAME DEPT.

SELECT COUNT(*),DNO
FROM EMP
GROUP BY DNO
HAVING COUNT(*)>1;


83. WAQTD THE NUMBER OF EMPS WHO JOINED ON SAME DAY.

SELECT COUNT(*),DOJ
FROM EMP
GROUP BY DOJ
HAVING COUNT(*)>1;

84. WAQTD THE NUMBER OF EMPS WHO ARE GETTING SAME SAL, WORKING IN SAME DEPT.

SELECT COUNT(*),SAL,DNO
FROM EMP
GROUP BY SAL,DNO
HAVING COUNT(*)>1;

85. WAQTD THE REPEATED LNAME FROM EMP TABLE.

SELECT LNAME
FROM EMP
GROUP BY LNAME
HAVING COUNT(*)>1;

86. WAQTD THE DUPLICATE JOB ROLES(REPEATED JOB ROLES).

SELECT JOB
FROM EMP
GROUP BY JOB
HAVING COUNT(*)>1;

87. WAQTD THE NUMBER OF EMPS WORKING IN SAME DEPT AND HIRED ON SAME DAY.

SELECT COUNT(*),DOJ,DNO
FROM EMP
GROUP BY DNO,DOJ
HAVING COUNT(*)>1;

88. WAQTD THE NUMBER OF EMPS WHO WARE WORKING IN SAME DEPT AND REPORTING TO SAME MANAGER.

SELECT COUNT(*),DNO,MGR
FROM EMP
GROUP BY DNO,MGR
HAVING COUNT(*)>1;

89. WAQTD THE NUMBER OF EMPS WHO ARE GETTINF SALARY MORE THAN OR EQUAL TO 30000 AND MAX SALARY LESS THAN OR EQUAL TO 150000 IN EACH DEPT.

SELECT COUNT(*),DNO
FROM EMP
WHERE SAL>=30000
GROUP BY DNO
HAVING MAX(SAL)<=150000;

90. WAQTD THE AVG SALARY GIVEN IN EACH DEPT IF THE DEPT HAS ATLEAST 4 EMPS.

SELECT AVG(SAL), DNO
FROM EMP
GROUP BY DNO
HAVING COUNT(*) >= 4;

91. WAQTD THE TOTAL SALARY GIVEN TO EACH DEPT IF THE MIN SALARY OF THE DEPT IS GREATER THAN 25000.

SELECT SUM(SAL), DNO
FROM EMP
GROUP BY DNO
HAVING MIN(SAL) > 25000;
