195. WAQTD THE EMP FNAME AND HIS DEPT NAME.

SELECT FNAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;

196. WAQTD THE CUSTOMER FIRST NAME AND HIS LOCATION.

SELECT FIRST_NAME,LOCATION
FROM CUSTOMER INNER JOIN LOCATION
ON CUSTOMER.LID=LOCATION.LID;

197. WAQTD THE EMP FNAME, DEPT NAME, JOB, SAL IF THE EMP IS WORKING AS SALESMAN OR MANAGER.

SELECT FNAME, DNAME,JOB, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE JOB IN ('SALESMAN','MANAGER');

198. WAQTD THE EMP FNAME, ORDER ID IF THE EMP HAS DELIVERED ANY PRODUCT.

SELECT FNAME, ORDER_ID
FROM EMP INNER JOIN ORDERS
ON EMP.EID=ORDERS.EID;

199. WAQTD THE EMP FULLNAME, DNAME IF THE EMP IS WORKING IN IT OR SALES DEPT.

SELECT CONCAT(FNAME,' ',LNAME) FULLNAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE DNAME IN ('IT','SALES');

200. WAQTD THE EMP FULLNAME, DEPT NAME IN THE BELOW FORMAT.

EMP-INFO
--------------------
Siddarth.P, IT

SELECT CONCAT(FNAME,'.',LEFT(LNAME,1),', ',DNAME) EMP_INFO
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;

201. WAQTD THE CUSTOMER FULLNAME AND LOCATION, CITY, STATE IF THE CUSTOMER IS LIVING IN KARNATAKA.

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) FULLNAME, LOCATION, CITY, STATE
FROM CUSTOMER INNER JOIN LOCATION
ON CUSTOMER.LID=LOCATION.LID
WHERE STATE='KARNATAKA';

202. WAQTD THE EMP FNAME, DNAME AND DNO.

SELECT E.FNAME, D.DNAME, D.DNO
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO;

203. WAQTD THE EMP FULL NAME AND DEPT NAME IF THE EMP IS WORKING AS SALESMAN.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME,D.DNAME
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO
WHERE E.JOB='SALESMAN';

204. WAQTD THE DEPT NAME AND ITS LOCATION.

SELECT D.DNAME,L.LOCATION
FROM DEPT D INNER JOIN LOCATION L
ON D.LID=L.LID;

205. WAQTD THE EMP FIRST NAME, DEPT NAME, JOB, SAL IF THE EMP FNAME START WITH VOWELS.

SELECT E.FNAME, D.DNAME, E.JOB,E.SAL
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO
WHERE LEFT(E.FNAME,1)IN('A','E','I','O','U');

