195. WAQTD THE EMP FNAME AND HIS DEPT NAME.

SELECT FNAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;

196. WAQTD THE CUSTOMER FIRST NAME AND HIS LOCATION.

SELECT FIRST_NAME,LOCATION
FROM CUSTOMER INNER JOIN LOCATION
ON CUSTOMER.LID=LOCATION.LID;

197. WAQTD THE EMP FNAME, DEPT NAME, JOB, SAL IF THE EMP IS WORKING AS SALESMAN OR MANAGER.

SELECT FNAME, DNAME,JOB, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE JOB IN ('SALESMAN','MANAGER');

198. WAQTD THE EMP FNAME, ORDER ID IF THE EMP HAS DELIVERED ANY PRODUCT.

SELECT FNAME, ORDER_ID
FROM EMP INNER JOIN ORDERS
ON EMP.EID=ORDERS.EID;

199. WAQTD THE EMP FULLNAME, DNAME IF THE EMP IS WORKING IN IT OR SALES DEPT.

SELECT CONCAT(FNAME,' ',LNAME) FULLNAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE DNAME IN ('IT','SALES');

200. WAQTD THE EMP FULLNAME, DEPT NAME IN THE BELOW FORMAT.

EMP-INFO
--------------------
Siddarth.P, IT

SELECT CONCAT(FNAME,'.',LEFT(LNAME,1),', ',DNAME) EMP_INFO
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;

201. WAQTD THE CUSTOMER FULLNAME AND LOCATION, CITY, STATE IF THE CUSTOMER IS LIVING IN KARNATAKA.

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) FULLNAME, LOCATION, CITY, STATE
FROM CUSTOMER INNER JOIN LOCATION
ON CUSTOMER.LID=LOCATION.LID
WHERE STATE='KARNATAKA';

202. WAQTD THE EMP FNAME, DNAME AND DNO.

SELECT E.FNAME, D.DNAME, D.DNO
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO;

203. WAQTD THE EMP FULL NAME AND DEPT NAME IF THE EMP IS WORKING AS SALESMAN.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME,D.DNAME
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO
WHERE E.JOB='SALESMAN';

204. WAQTD THE DEPT NAME AND ITS LOCATION.

SELECT D.DNAME,L.LOCATION
FROM DEPT D INNER JOIN LOCATION L
ON D.LID=L.LID;

205. WAQTD THE EMP FIRST NAME, DEPT NAME, JOB, SAL IF THE EMP FNAME START WITH VOWELS.

SELECT E.FNAME, D.DNAME, E.JOB,E.SAL
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO
WHERE LEFT(E.FNAME,1)IN('A','E','I','O','U');

206. WAQTD THE CUSTOMER FIRST NAME, ORDER ID
{Note: Order Id will be displayed only if the customers have ordered any product}

SELECT C.FIRST_NAME, O.ORDER_ID
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CID=O.CID;

207. WAQTD THE PRODUCT NAME, ORDER ID.
{Note: Order Id will be displayed only if the product has been ordered.}

SELECT P.PNAME, O.ORDER_ID
FROM PRODUCT P INNER JOIN ORDERS O
ON P.PRODUCT_ID=O.PRODUCT_ID;

208. WAQTD THE ORDER ID, CUSTOMER FIRST NAME AND THE PRODUCT NAME WHICH HE HAS ORDERED.

SELECT O.ORDER_ID,C.FIRST_NAME,P.PNAME
FROM ORDERS O INNER JOIN CUSTOMER C
ON O.CID=C.CID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID;

209. WAQTD THE EMP FNAME, DEPT NAME AND DEPT LOCATION.

SELECT E.FNAME, D.DNAME, L.LOCATION
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO INNER JOIN LOCATION L
ON D.LID=L.LID;

210. WAQTD THE CUSTOMER FULLNAME, PRODUCT PNAME, PRICE AS BILL WITH 18% GST.

FULLNAME   PNAME   BILL  BILL_WITH_GST
RAVI RAI   BALL    20.0    23.6

SELECT CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) FULLNAME,
       P.PNAME,P.PRICE BILL,
       ROUND(P.PRICE+(P.PRICE*0.18)) GST_BILL
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CID=O.CID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID;

211. WAQTD THE CUSTOMER FULLNAME, ORDER ID, PRODUCT NAME, PRICE AS BILL, GST_BILL, DELIVERY ADDRESS AS BELOW.

CUSTOMER  ORDER_ID  PNAME  BILL GST_BILL  DELIVERY_ADDRESS  
---------------------------------------------------------------------
RAVI.R      1111    WATCH  1000  1180     YELAHANKA, BANGALORE, KARNATAKA
FNAME.L    OID      PNAME  PRICE PRC+18%  LOCATION, CITY, STATE


SELECT CONCAT(C.FIRST_NAME,' ',C.LAST_NAME) FULLNAME,
       O.ORDER_ID, P.PNAME, P.PRICE BILL,
       P.PRICE+(P.PRICE*0.18) GST_BILL,
       CONCAT(L.LOCATION,', ',L.CITY,', ',L.STATE) DELIVERY_ADDRESS
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CID=O.CID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID INNER JOIN LOCATION L
ON C.LID=L.LID;

212. WAQTD THE EMP FULLNAME, ORDER ID AND PRODUCT NAME WHICH HE HAS DELIVERED.

SELECT CONCAT(E.FNAME,' ',E.LNAME) FULLNAME, O.ORDER_ID, P.PNAME
FROM EMP E INNER JOIN ORDERS O
ON E.EID=O.EID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID;

