195. WAQTD THE EMP FNAME AND HIS DEPT NAME.

SELECT FNAME,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;

196. WAQTD THE CUSTOMER FIRST NAME AND HIS LOCATION.

SELECT FIRST_NAME,LOCATION
FROM CUSTOMER INNER JOIN LOCATION
ON CUSTOMER.LID=LOCATION.LID;

197. WAQTD THE EMP FNAME, DEPT NAME, JOB, SAL IF THE EMP IS WORKING AS SALESMAN OR MANAGER.

SELECT FNAME, DNAME,JOB, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE JOB IN ('SALESMAN','MANAGER');

198. WAQTD THE EMP FNAME, ORDER ID IF THE EMP HAS DELIVERED ANY PRODUCT.

SELECT FNAME, ORDER_ID
FROM EMP INNER JOIN ORDERS
ON EMP.EID=ORDERS.EID;

199. WAQTD THE EMP FULLNAME, DNAME IF THE EMP IS WORKING IN IT OR SALES DEPT.

SELECT CONCAT(FNAME,' ',LNAME) FULLNAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO
WHERE DNAME IN ('IT','SALES');

200. WAQTD THE EMP FULLNAME, DEPT NAME IN THE BELOW FORMAT.

EMP-INFO
--------------------
Siddarth.P, IT

SELECT CONCAT(FNAME,'.',LEFT(LNAME,1),', ',DNAME) EMP_INFO
FROM EMP INNER JOIN DEPT
ON EMP.DNO=DEPT.DNO;
