40. WAQTD THE DETAILS OF EMP WHOSE FNAME STARTS WITH S.

SELECT *
FROM EMP
WHERE FNAME LIKE 'S%';

41. WAQTD THE FNAME, LNAME OF THE EMP IF THE EMP FNAME ENDS WITH H.

SELECT FNAME,LNAME
FROM EMP
WHERE FNAME LIKE '%H';

42. WAQTD THE FNAME, JOB IF THE JOB ROLE CONTAINS MAN IN IT.

SELECT FNAME, JOB
FROM EMP
WHERE JOB LIKE '%MAN%';

43. WAQTD THE DETAILS OF EMP IF THE EMP WAS BORN IN THE YEAR 1995 USING LIKE OPERATOR.

SELECT *
FROM EMP
WHERE DOB LIKE '1995%';

44. WAQTD THE DETAILS OF EMP IF THE EMP FNAME 3RD CHARACTER IS R.

SELECT *
FROM EMP
WHERE FNAME LIKE '__R%';

45. WAQTD THE EMP FNAME WHOSE FNAME DOESNOT START WITH A.

SELECT FNAME
FROM EMP
WHERE FNAME NOT LIKE 'A%';

46. WAQTD THE DETAILS OF EMP IF THE EMP FNAME STARTS WITH S OR A.

SELECT *
FROM EMP
WHERE FNAME LIKE 'S%' OR FNAME LIKE 'A%';

47. WAQTD THE EMP FNAME, LNAME, JOB IF THE EMP FNAME STARTS WITH S BUT LAST NAME ENDS WITH L.

SELECT FNAME,LNAME,JOB
FROM EMP
WHERE FNAME LIKE 'S%' AND LNAME LIKE '%L';