40. WAQTD THE DETAILS OF EMP WHOSE FNAME STARTS WITH S.

SELECT *
FROM EMP
WHERE FNAME LIKE 'S%';

41. WAQTD THE FNAME, LNAME OF THE EMP IF THE EMP FNAME ENDS WITH H.

SELECT FNAME,LNAME
FROM EMP
WHERE FNAME LIKE '%H';

42. WAQTD THE FNAME, JOB IF THE JOB ROLE CONTAINS MAN IN IT.

SELECT FNAME, JOB
FROM EMP
WHERE JOB LIKE '%MAN%';

43. WAQTD THE DETAILS OF EMP IF THE EMP WAS BORN IN THE YEAR 1995 USING LIKE OPERATOR.

SELECT *
FROM EMP
WHERE DOB LIKE '1995%';

44. WAQTD THE DETAILS OF EMP IF THE EMP FNAME 3RD CHARACTER IS R.

SELECT *
FROM EMP
WHERE FNAME LIKE '__R%';

45. WAQTD THE EMP FNAME WHOSE FNAME DOESNOT START WITH A.

SELECT FNAME
FROM EMP
WHERE FNAME NOT LIKE 'A%';

46. WAQTD THE DETAILS OF EMP IF THE EMP FNAME STARTS WITH S OR A.

SELECT *
FROM EMP
WHERE FNAME LIKE 'S%' OR FNAME LIKE 'A%';

47. WAQTD THE EMP FNAME, LNAME, JOB IF THE EMP FNAME STARTS WITH S BUT LAST NAME ENDS WITH L.

SELECT FNAME,LNAME,JOB
FROM EMP
WHERE FNAME LIKE 'S%' AND LNAME LIKE '%L';

48. WAQTD THE DETAILS OF EMP IF THE EMP FNAME STARTS WITH S OR K BUT FNAME ENDS WITH H OR N.

SELECT *
FROM EMP
WHERE (FNAME LIKE 'S%' OR FNAME LIKE 'K%') AND 
(FNAME LIKE '%H' OR FNAME LIKE '%N');

49. WAQTD THE DETAILS OF EMP IF THE EMP FNAME STARTS WITH VOWELS.

SELECT *
FROM EMP
WHERE FNAME LIKE 'A%' OR
      FNAME LIKE 'E%' OR
      FNAME LIKE 'I%' OR
      FNAME LIKE 'O%' OR
      FNAME LIKE 'U%';

50. WAQTD THE DETAILS OF EMP WHO WERE NOT HIRED IN 2021.

SELECT *
FROM EMP
WHERE DOJ NOT LIKE '2021%';



51. WAQTD THE EMP FNAME, LNAME IF THE EMP FNAME DOESNOT START WITH S OR K OR A.

SELECT FNAME,LNAME
FROM EMP
WHERE FNAME NOT LIKE 'S%' AND FNAME NOT LIKE 'K%' AND FNAME NOT LIKE 'A%';

52. WAQTD THE STUD NAMES IF THE STUD NAMES CONTAIN ATLEAST 1 %.

SELECT NAME
FROM STUD
WHERE NAME LIKE '%\%%';

53. WAQTD THE STUD NAMES IF THE STUDD NAMES CONTAIN ATLEST 1 _.

SELECT NAME
FROM STUD
WHERE NAME LIKE '%\_%';

54. WAQTD THE STUD NAMES IF THE STUDD NAMES CONTAIN ATLEST 2 %.

SELECT NAME
FROM STUD
WHERE NAME LIKE '%\%%\%%';

55. WAQTD THE STUD NAMES IF THE STUDD NAMES CONTAIN ATLEST 2 _.

SELECT NAME
FROM STUD
WHERE NAME LIKE '%\_%\_%';

56. WAQTD THE EMP FNAME, LNAME, JOB IF THE EMP FNAME STARTS WITH S BUT LAST NAME ENDS WITH L.

SELECT FNAME,LNAME,JOB
FROM EMP
WHERE FNAME LIKE 'S%' AND LNAME LIKE '%L';
