131. WAQTD THE AVG SALARY IN EVERY DEPT. ROUND OFF THE AVG SALARY TO 100'S PLACE.

SELECT ROUND(AVG(SAL),-2),DNO
FROM EMP
GROUP BY DNO;

132. WAQTD THE DETAILS OF EMP WHO HAVE EVEN EID.

SELECT *
FROM EMP
WHERE MOD(EID,2)=0;

133. WAQTD THE EMP FNAME, JOB, SALARY IF THE EMP FNAME CONTAINS EVEN LENGTH.

SELECT FNAME,JOB,SAL
FROM EMP
WHERE MOD(LENGTH(FNAME),2)=0;

134. WAQTD THE FNAME, AND DOB IN US FORMAT.

MM/DD/YYYY

FNAME  |  DOB
---------------
Hema    02/26/2026

SELECT FNAME,DATE_FORMAT(DOB,'%m/%d/%Y') DOB
FROM EMP;

135. WAQTD THE DETAILS OF EMP IF THE EMP WAS HIRED IN THE YEAR 2021 USING DATE FUNCTIONS.

SELECT *
FROM EMP
WHERE YEAR(DOJ)=2021;

136. WAQTD THE EMP FNAME, DOB IF THE EMP WAS BORN IN THE MONTH OF FEBRUARY OR MARCH.

SELECT FNAME,DOB
FROM EMP
WHERE MONTH(DOB)IN(2,3);

137. WAQTD THE DETAILS OF EMP WHO WERE HIRED ON SAT OR SUN.

SELECT *
FROM EMP
WHERE DATE_FORMAT(DOJ,'%a')IN('SAT','SUN');

138. WAQTD THE EMP FNAME, DOB IF THEY WERE BORN IN EVEN YEARS.

SELECT FNAME,DOB
FROM EMP
WHERE MOD(YEAR(DOB),2)=0;

139. WAQTD THE EMP FNAME, DOJ IF THE EMP WAS JOINED IN LEAP YEAR.
{Hint :
 * Year must be divisible 4 or 400 but not divisible by 100.
}

SELECT FNAME,DOJ
FROM EMP
WHERE 
(MOD(YEAR(DOJ),4)=0 OR MOD(YEAR(DOJ),400)=0) AND 
MOD(YEAR(DOJ),100)!=0;

140. WAQTD THE NUMBER OF EMPS HIRED EVERY YEAR.

SELECT YEAR(DOJ),COUNT(*)
FROM EMP
GROUP BY YEAR(DOJ);

141. WAQTD THE FNAME, YEAR OF EXPERIENCE FROM EMP TABLE.

SELECT FNAME, YEAR(CURDATE())-YEAR(DOJ) EXPERIENCE
FROM EMP;

142. WAQTD THE FNAME, MONTH-DATE OF THE EMP WHO HAVE THEIR NEAREST 3 UPCOMING BIRTHDAYS.

SELECT FNAME,DATE_FORMAT(DOB,'%m-%d') BIRTH_DAY
FROM EMP
WHERE DATE_FORMAT(CURDATE(),'%m-%d')<DATE_FORMAT(DOB,'%m-%d')
ORDER BY BIRTH_DAY
LIMIT 3;

143. WAQTD THE CURRENT AGE OF ALL THE EMPS. (in number of years).

SELECT FNAME, YEAR(CURDATE())-YEAR(DOB) AGE
FROM EMP;
