22. WAQTD THE DETAILS, ALONG WITH ANNUAL SALARY IF THE EMP IS GETTING ANNUAL SALARY LESS THAN 600000.

SELECT *,SAL*12 ANNUAL_SAL
FROM EMP
WHERE SAL*12<600000;

23. WAQTD THE EMP FNAME, JOB, SAL IF THE EMP IS WORKING AS DISPATCHER AND GETTING SALARY MORE THAN 32000.

SELECT FNAME,JOB,SAL
FROM EMP
WHERE JOB='DISPATCHER' AND SAL>32000;

24. WAQTD THE EMP FNAME, JOB, DNO, SAL IF THE EMP IS WORKING AS SALESMAN IN DEPT 111.

SELECT FNAME,JOB,DNO,SAL
FROM EMP
WHERE JOB='SALESMAN' AND DNO=111;

25. WAQTD THE DETAILS OF EMP IF THE EMP IS WORKINGAS SALESMAN OR MANAGER.

SELECT *
FROM EMP
WHERE JOB='SALESMAN' OR JOB='MANAGER';

26. WAQTD THE DETAILS OF EMP IF THE EMP IS WORKING AS SALESMAN OR MANAGER OR DISPATCHER.

SELECT *
FROM EMP
WHERE JOB='SALESMAN' OR JOB='MANAGER' OR JOB='DISPATCHER';

27. WAQTD THE EMP FNAME, JOB, SAL, DNO IF THE EMP IS WORKING AS SALESMAN OR MANAGER IN DEPT 110, 111 OR 112.

SELECT FNAME,JOB,SAL,DNO
FROM EMP
WHERE (JOB='SALESMAN' OR JOB='MANAGER')AND(DNO=110 OR DNO=111 OR DNO=112);

28. WAQTD THE DETAILS OF EMP IF THE EMP IS WORKING AS SALESMAN, MANAGER, DISPATCHER OR DEVELOPER.

SELECT *
FROM EMP
WHERE JOB='SALESMAN' OR JOB='MANAGER' OR JOB='DISPATCHER' OR JOB='DEVELOPER';
