89. WAQTD THE DETAILS OF EMP ON THE BASIS OF SAL FROM MAX TO MIN.

SELECT *
FROM EMP
ORDER BY SAL DESC;

90. WAQTD THE EMP FNAME, LNAME, SAL, DNO. DISPLAY THE DATA ON THE BASES OF DNO IN DESC ORDER.

SELECT FNAME,LNAME,SAL,DNO
FROM EMP
ORDER BY DNO DESC;

91. WAQTD THE FNAME, LNAME AND DISPLAY THE RECORDS ACC TO FNAME IN ALPHABETICAL ORDER.

SELECT FNAME,LNAME
FROM EMP
ORDER BY FNAME ASC;

92. WAQTD THE NUMBER OF EMPS, MAX SAL, MIN SAL IF THE EMP IS GETTING SALARY MORE THAN 30000 AND IF THE DEPT HAS ATLEAST 2 EMPS WORKING.
ARRANGE THE RECORDS BASED ON MAX SAL IN DESC ORDER.

SELECT COUNT(*),MAX(SAL),MIN(SAL),DNO
FROM EMP
WHERE SAL>30000
GROUP BY DNO
HAVING COUNT(*)>=2
ORDER BY MAX(SAL) DESC;

93. WAQTD THE FNAME, LNAME, SALARY. ARRANGE THE RECORDS BASED ON THEIR SAL IN DESC ORDER AND SECONDARY SORT ACCORDING TO THEIR FNAME IN ALPHABETICAL ORDER.

SELECT FNAME,LNAME,SAL
FROM EMP
ORDER BY SAL DESC,FNAME ASC;

94. WAQTD THE FNAME, LNAME, JOB, AND SALARY OF EMPLOYEES. ARRANGE THE RECORDS BASED ON JOB IN ALPHABETICAL ORDER AND SECONDARY SORT ACCORDING TO SALARY IN DESC ORDER.

SELECT FNAME, LNAME, JOB, SAL
FROM EMP
ORDER BY JOB ASC, SAL DESC;

95. WAQTD THE DNO, NUMBER OF EMPS, AVERAGE SALARY, AND TOTAL SALARY OF EACH DEPARTMENT. DISPLAY ONLY THOSE DEPARTMENTS WHOSE AVERAGE SALARY IS GREATER THAN 40000. ARRANGE THE RECORDS BASED ON AVERAGE SALARY IN DESC ORDER.

SELECT DNO, COUNT(*) AS NO_OF_EMPS, AVG(SAL) AS AVG_SAL, SUM(SAL) AS TOTAL_SAL
FROM EMP
GROUP BY DNO
HAVING AVG(SAL) > 40000
ORDER BY AVG(SAL) DESC;
