124. 
 Inp1   Inp2   Output
PREETI   E      2
MALAYALAM A     4

SELECT 
LENGTH('MALAYALAM')- 
LENGTH(REPLACE('MALAYALAM','A',''));

125. WAQTD THE DETAILS OF EMP IS THE EMP FNAME CONTAINS EXACTLY 1 H IN IT.
{hint: Previous Logic}


SELECT *
FROM EMP
WHERE LENGTH(FNAME)-LENGTH(REPLACE(lower(FNAME),'h',''))=1;
            
126. WAQTD THE DETAILS OF EMPP IF THE EMP FNAME CONTAINS EXATLY 2 A IN IT.

Abhijit  X
Dilip    X 
Aman

SELECT *
FROM EMP
WHERE LENGTH(FNAME)-LENGTH(REPLACE(LOWER(FNAME),'a',''))=2;

127. WAQTD THE DETAILS OF EMP IF THE EMP FNAME DOES NOT CONTAIN THE LETTER 'A'.
SELECT *
FROM EMP
WHERE LENGTH(FNAME)-LENGTH(REPLACE(LOWER(FNAME),'a',''))=0;
