213. WAQTD THE EMP FNAME AND HIS MANAGER FNAME.

SELECT E1.FNAME EMP_NAME, E2.FNAME MANAGER_NAME
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

214. WAQTD THE EMP FNAME, SALARY, MANAGER FNAME AND HIS SALARY.

SELECT E1.FNAME, E1.SAL, E2.FNAME, E2.SAL
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

215. WAQTD THE EMP FIRST NAME, SALARY AND DEPT NO ALONG WITH MANAGER FNAME, SALARY AND DEPT NO IF THE EMP AND MANAGER ARE WORKING IN SAME DEPT.

SELECT E1.FNAME, E1.SAL,E1.DNO,E2.FNAME, E2.SAL, E2.DNO
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DNO=E2.DNO;

216. WAQTD THE EMP FNAME, DOB AND HIS MANAGER FNAME, DOB IF THE EMP IS ELDER THAN HIS MANAGER.

SELECT E1.FNAME, E1.DOB, E2.FNAME, E2.DOB
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DOB<E2.DOB;

217. WAQTD THE EMP FNAME, GENDER AND MANAGER FNAME, HIS GENDER IF THEY HAVE SAME GENDER.

SELECT E1.FNAME, E1.GENDER, E2.FNAME, E2.GENDER 
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.GENDER=E2.GENDER;
