213. WAQTD THE EMP FNAME AND HIS MANAGER FNAME.

SELECT E1.FNAME EMP_NAME, E2.FNAME MANAGER_NAME
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

214. WAQTD THE EMP FNAME, SALARY, MANAGER FNAME AND HIS SALARY.

SELECT E1.FNAME, E1.SAL, E2.FNAME, E2.SAL
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

215. WAQTD THE EMP FIRST NAME, SALARY AND DEPT NO ALONG WITH MANAGER FNAME, SALARY AND DEPT NO IF THE EMP AND MANAGER ARE WORKING IN SAME DEPT.

SELECT E1.FNAME, E1.SAL,E1.DNO,E2.FNAME, E2.SAL, E2.DNO
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DNO=E2.DNO;

216. WAQTD THE EMP FNAME, DOB AND HIS MANAGER FNAME, DOB IF THE EMP IS ELDER THAN HIS MANAGER.

SELECT E1.FNAME, E1.DOB, E2.FNAME, E2.DOB
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DOB<E2.DOB;

217. WAQTD THE EMP FNAME, GENDER AND MANAGER FNAME, HIS GENDER IF THEY HAVE SAME GENDER.

SELECT E1.FNAME, E1.GENDER, E2.FNAME, E2.GENDER 
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.GENDER=E2.GENDER;

218. WAQTD THE EMP FNAME, DEPT NAME AND HIS MANAGER FNAME.

SELECT E1.FNAME EMP_NAME, D1.DNAME, E2.FNAME MANAGER_NAME
FROM EMP E1 INNER JOIN DEPT D1
ON E1.DNO=D1.DNO JOIN EMP E2
ON E1.MGR=E2.EID;

219. WAQTD THE EMP FNAME, HIS DEPT NAME ALONG WITH MANAGER FNAME AND HIS DEPT NAME IF EMP AND HIS MANAGER WORK IN DIFFERENT DEPTS.

SELECT E1.FNAME, D1.DNAME, E2.FNAME, D2.DNAME
FROM EMP E1 INNER JOIN DEPT D1
ON E1.DNO=D1.DNO JOIN EMP E2
ON E1.MGR=E2.EID INNER JOIN DEPT D2
ON E2.DNO=D2.DNO
WHERE E1.DNO!=E2.DNO;

220. WAQTD THE EMP FULLNAME AND MANAGER FULLNAME IN THE BELOW FORMAT.

REPORTINGS
------------
Hema Shetty reporting to Siddarth Patil

SELECT 
CONCAT(E1.FNAME,' ',E1.LNAME,' is reporting to ',E2.FNAME,' ',E2.LNAME)
REPORTINGS
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

221. WAQTD THE BILL IN BELOW FORMAT.

CUSTOMER NAME   PRODUCT  PRICE  GST_AMT TOTAL_BILL 
-------------- --------- ------ ------- ----------
Ravi.S           Watch   2000.0  360.0    2360.0

ORDER_ID    ORDERED_ON     DELIVERED_ON    Delivered_By
--------  --------------   ------------    ------------
 1111     Mar 10th, 2026   Mar 11th, 2026    Kumar(e.fname)

Address
-------
Koramangala, Bangalore, Karnataka


SELECT CONCAT(C.FIRST_NAME,'.',LEFT(C.LAST_NAME,1)) CUSTOMER_NAME,
       P.PNAME PRODUCT, 
       P.PRICE, 
       P.PRICE*0.18 GST_BILL,
       P.PRICE+(P.PRICE*0.18) TOTAL_BILL,
       O.ORDER_ID,
       DATE_FORMAT(O.ORDER_DATE,'%b %D, %Y') ORDERED_ON,
       DATE_FORMAT(O.DELIVERY_DATE,'%b %D, %Y') DELIVERED_ON,
       E.FNAME DELIVERED_BY,
       CONCAT(L.LOCATION,', ',L.CITY,', ',L.STATE) ADDRESS

FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CID=O.CID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID INNER JOIN LOCATION L
ON C.LID=L.LID INNER JOIN EMP E
ON O.EID=E.EID;

