213. WAQTD THE EMP FNAME AND HIS MANAGER FNAME.

SELECT E1.FNAME EMP_NAME, E2.FNAME MANAGER_NAME
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

214. WAQTD THE EMP FNAME, SALARY, MANAGER FNAME AND HIS SALARY.

SELECT E1.FNAME, E1.SAL, E2.FNAME, E2.SAL
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

215. WAQTD THE EMP FIRST NAME, SALARY AND DEPT NO ALONG WITH MANAGER FNAME, SALARY AND DEPT NO IF THE EMP AND MANAGER ARE WORKING IN SAME DEPT.

SELECT E1.FNAME, E1.SAL,E1.DNO,E2.FNAME, E2.SAL, E2.DNO
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DNO=E2.DNO;

216. WAQTD THE EMP FNAME, DOB AND HIS MANAGER FNAME, DOB IF THE EMP IS ELDER THAN HIS MANAGER.

SELECT E1.FNAME, E1.DOB, E2.FNAME, E2.DOB
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.DOB<E2.DOB;

217. WAQTD THE EMP FNAME, GENDER AND MANAGER FNAME, HIS GENDER IF THEY HAVE SAME GENDER.

SELECT E1.FNAME, E1.GENDER, E2.FNAME, E2.GENDER 
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID
WHERE E1.GENDER=E2.GENDER;

218. WAQTD THE EMP FNAME, DEPT NAME AND HIS MANAGER FNAME.

SELECT E1.FNAME EMP_NAME, D1.DNAME, E2.FNAME MANAGER_NAME
FROM EMP E1 INNER JOIN DEPT D1
ON E1.DNO=D1.DNO JOIN EMP E2
ON E1.MGR=E2.EID;

219. WAQTD THE EMP FNAME, HIS DEPT NAME ALONG WITH MANAGER FNAME AND HIS DEPT NAME IF EMP AND HIS MANAGER WORK IN DIFFERENT DEPTS.

SELECT E1.FNAME, D1.DNAME, E2.FNAME, D2.DNAME
FROM EMP E1 INNER JOIN DEPT D1
ON E1.DNO=D1.DNO JOIN EMP E2
ON E1.MGR=E2.EID INNER JOIN DEPT D2
ON E2.DNO=D2.DNO
WHERE E1.DNO!=E2.DNO;

220. WAQTD THE EMP FULLNAME AND MANAGER FULLNAME IN THE BELOW FORMAT.

REPORTINGS
------------
Hema Shetty reporting to Siddarth Patil

SELECT 
CONCAT(E1.FNAME,' ',E1.LNAME,' is reporting to ',E2.FNAME,' ',E2.LNAME)
REPORTINGS
FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EID;

221. WAQTD THE BILL IN BELOW FORMAT.

CUSTOMER NAME   PRODUCT  PRICE  GST_AMT TOTAL_BILL 
-------------- --------- ------ ------- ----------
Ravi.S           Watch   2000.0  360.0    2360.0

ORDER_ID    ORDERED_ON     DELIVERED_ON    Delivered_By
--------  --------------   ------------    ------------
 1111     Mar 10th, 2026   Mar 11th, 2026    Kumar(e.fname)

Address
-------
Koramangala, Bangalore, Karnataka


SELECT CONCAT(C.FIRST_NAME,'.',LEFT(C.LAST_NAME,1)) CUSTOMER_NAME,
       P.PNAME PRODUCT, 
       P.PRICE, 
       P.PRICE*0.18 GST_BILL,
       P.PRICE+(P.PRICE*0.18) TOTAL_BILL,
       O.ORDER_ID,
       DATE_FORMAT(O.ORDER_DATE,'%b %D, %Y') ORDERED_ON,
       DATE_FORMAT(O.DELIVERY_DATE,'%b %D, %Y') DELIVERED_ON,
       E.FNAME DELIVERED_BY,
       CONCAT(L.LOCATION,', ',L.CITY,', ',L.STATE) ADDRESS

FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CID=O.CID INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID INNER JOIN LOCATION L
ON C.LID=L.LID INNER JOIN EMP E
ON O.EID=E.EID;

222. WAQTD THE EMP FNAME, DEPT NAME, MANAGER FNAME, DEPT NAME IF THE EMP AND MANAGER IS WORKING IN SAME DEPT.

SELECT E1.FNAME, D1.DNAME, E2.FNAME, D2.DNAME
FROM EMP E1 INNER JOIN DEPT D1
ON E1.DNO=D1.DNO JOIN EMP E2
ON E1.MGR=E2.EID INNER JOIN DEPT D2
ON E2.DNO=D2.DNO
WHERE D1.DNO=D2.DNO;

223. WAQTD THE CUSTOMER FIRST NAME AND LAST NAME, LOCATION NAME IF THE CUSTOMER IS NOT LIVING IN KARNATAKA.

SELECT C.FIRST_NAME, C.LAST_NAME, L.LOCATION
FROM CUSTOMER C INNER JOIN LOCATION L
ON C.LID=L.LID
WHERE L.STATE!='KARNATAKA';

224. WAQTD THE CUSTOMER FNAME, TOTAL NUMBERS OF ORDERS MADE BY HIM. DISPLAY THE RECORDS BASED ON NUMBER OF ORDERS FROM MAX TO MIN.

SELECT COUNT(*),O.CID,C.FIRST_NAME
FROM ORDERS O INNER JOIN CUSTOMER C
ON O.CID=C.CID
GROUP BY O.CID,C.FIRST_NAME
ORDER BY COUNT(*) DESC;

225. WAQTD THE DEPT NAME, NUMBER OF EMPS IN EACH DEPT. 

SELECT COUNT(*),E.DNO,D.DNAME
FROM EMP E INNER JOIN DEPT D
ON E.DNO=D.DNO
GROUP BY E.DNO,D.DNAME;

226. WAQTD THE TOP 3 PNAMES WHICH HAS SOLD THE MOST BASED ON NUMBER OF PRODUCTS.

SELECT COUNT(*),O.PRODUCT_ID,P.PNAME
FROM ORDERS O INNER JOIN PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID
GROUP BY O.PRODUCT_ID,P.PNAME
ORDER BY COUNT(*) DESC
LIMIT 3;

227. WAQTD THE NUMBER OF PRODUCTS DELIVERED EVERY MONTH.

month   num_of_products
------------------------
March     3
April     5

SELECT COUNT(*),DATE_FORMAT(DELIVERY_DATE,'%M') month
FROM ORDERS
GROUP BY month;

228. WAQTD THE NUMBER OF CUSTOMERS, STATE LIVING IN EACH STATE.

SELECT COUNT(*),L.STATE
FROM CUSTOMER C INNER JOIN LOCATION L
ON C.LID=L.LID
GROUP BY L.STATE;

229. WAQTD THE NUMBER OF DEPTS, CITY LOCATED IN EVERY CITY.

SELECT COUNT(*),L.CITY
FROM DEPT D INNER JOIN LOCATION L
ON D.LID=L.LID
GROUP BY L.CITY;

230. WAQTD THE NUMBER OF ORDERS, EMP FNAME DELIVERED BY EVERY EMP.

SELECT COUNT(*),O.EID, E.FNAME
FROM EMP E INNER JOIN ORDERS O
ON O.EID=E.EID
GROUP BY O.EID,E.FNAME;

231. WAQTD THE CUSTOMER FNAME, ORDER ID IF THEY HAVE ORDERED THE PRODUCT OR EVEN THEY HAVE NOT ORDERED ANY PRODUCT.

SELECT C.FIRST_NAME, O.ORDER_ID
FROM CUSTOMER C LEFT OUTER JOIN ORDERS O
ON C.CID=O.CID
ORDER BY ORDER_ID;



