144. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY MORE THAN KIRAN'S SALARY.

SELECT * FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='KIRAN');

145. WAQTD THE EMP FNAME, SAL IF THE EMP IS GETTING SALARY LESS THAN SAMEER.

SELECT FNAME,SAL FROM EMP WHERE SAL<
(SELECT SAL FROM EMP WHERE FNAME='SAMEER');

146. WAQTD THE DETAILS OF EMP WHO IS WORKING SAME AS KARAN'S JOB ROLE.

SELECT *  FROM EMP WHERE JOB=
(SELECT JOB FROM EMP WHERE FNAME='KARAN');

147. WAQTD THE EMP FNAME, DOJ IF THE EMP JOINED AFTER MURALI.

SELECT FNAME, DOJ FROM EMP WHERE DOJ>
(SELECT DOJ FROM EMP WHERE FNAME='MURALI');

148. WAQTD THE DETAILS OF EMP WHO IS WORKING AS SALESMAN AND GETTING SALARY MORE THAN DHARANI.

SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>
(SELECT SAL FROM EMP WHERE FNAME='DHARANI');

149. WAQTD THE EMP FNAME, JOB, SAL IF THE EMP IS GETTING SALARY MORE THAN PRIYA SALARY BUT LESS THAN RAHUL'S SALARY.

SELECT FNAME, JOB, SAL FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='PRIYA') AND SAL<
(SELECT SAL FROM EMP WHERE FNAME='RAHUL');

150. WAQTD THE DETAILS OF EMP WHO WERE BORN AFTER PRIYA.

SELECT * FROM EMP WHERE DOB>
(SELECT DOB FROM EMP WHERE FNAME='PRIYA');

151. WAQTD THE EMP FNAME, DOJ IF THE EMP WAS JOINED 2 YEARS AFTER SAMEER'S JOINING.

SELECT FNAME, DOJ FROM EMP WHERE DOJ>
(SELECT DATE_ADD(DOJ,INTERVAL 2 YEAR) FROM EMP WHERE FNAME='SAMEER');

152. WAQTD THE DETAILS OF EMP IF THE EMP IS 3 YEARS OR MORE YOUNGER THAN SAMEER.

SELECT * FROM EMP WHERE DOB>=
(SELECT DATE_ADD(DOB,INTERVAL 3 YEAR) FROM EMP WHERE FNAME='SAMEER');

153. WAQTD THE EMP FNAME, DOB IF THE EMP IS 2 YEAR OR MORE ELDER THAN FARIYA.

SELECT FNAME, DOB FROM EMP WHERE DOB<
(SELECT DATE_SUB(DOB,INTERVAL 2 YEAR) FROM EMP WHERE FNAME='FARIYA');

154. WAQTD THE DETAILS OF EMP IF THE EMP WAS NOT WORKING IN SAME DEPT AS RAHUL'S DEPT BUT GETTING SALARY MORE THAN DHARANI.

SELECT * FROM EMP WHERE DNO!=
(SELECT DNO FROM EMP WHERE FNAME='RAHUL') AND SAL>
(SELECT SAL FROM EMP WHERE FNAME='DHARANI');
 
155. WAQTD THE DEPT NAME OF AMAN.

SELECT DNAME FROM DEPT WHERE DNO=
(SELECT DNO FROM EMP WHERE FNAME='AMAN');

156. WAQTD THE DEPT NAME OF SAMEER.

SELECT DNAME FROM DEPT WHERE DNO=
(SELECT DNO FROM EMP WHERE FNAME='SAMEER');

157. WAQTD THE DETAILS OF CUSTOMER WHO LIVES IN KORAMANGALA.

SELECT * FROM CUSTOMER WHERE LID=
(SELECT LID FROM LOCATION WHERE LOCATION='KORAMANGALA');


