144. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY MORE THAN KIRAN'S SALARY.

SELECT * FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='KIRAN');

145. WAQTD THE EMP FNAME, SAL IF THE EMP IS GETTING SALARY LESS THAN SAMEER.

SELECT FNAME,SAL FROM EMP WHERE SAL<
(SELECT SAL FROM EMP WHERE FNAME='SAMEER');

146. WAQTD THE DETAILS OF EMP WHO IS WORKING SAME AS KARAN'S JOB ROLE.

SELECT *  FROM EMP WHERE JOB=
(SELECT JOB FROM EMP WHERE FNAME='KARAN');

147. WAQTD THE EMP FNAME, DOJ IF THE EMP JOINED AFTER MURALI.

SELECT FNAME, DOJ FROM EMP WHERE DOJ>
(SELECT DOJ FROM EMP WHERE FNAME='MURALI');

148. WAQTD THE DETAILS OF EMP WHO IS WORKING AS SALESMAN AND GETTING SALARY MORE THAN DHARANI.

SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>
(SELECT SAL FROM EMP WHERE FNAME='DHARANI');

149. WAQTD THE EMP FNAME, JOB, SAL IF THE EMP IS GETTING SALARY MORE THAN PRIYA SALARY BUT LESS THAN RAHUL'S SALARY.

SELECT FNAME, JOB, SAL FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='PRIYA') AND SAL<
(SELECT SAL FROM EMP WHERE FNAME='RAHUL');

150. WAQTD THE DETAILS OF EMP WHO WERE BORN AFTER PRIYA.

SELECT * FROM EMP WHERE DOB>
(SELECT DOB FROM EMP WHERE FNAME='PRIYA');

