144. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY MORE THAN KIRAN'S SALARY.

SELECT * FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='KIRAN');

145. WAQTD THE EMP FNAME, SAL IF THE EMP IS GETTING SALARY LESS THAN SAMEER.

SELECT FNAME,SAL FROM EMP WHERE SAL<
(SELECT SAL FROM EMP WHERE FNAME='SAMEER');

146. WAQTD THE DETAILS OF EMP WHO IS WORKING SAME AS KARAN'S JOB ROLE.

SELECT *  FROM EMP WHERE JOB=
(SELECT JOB FROM EMP WHERE FNAME='KARAN');

147. WAQTD THE EMP FNAME, DOJ IF THE EMP JOINED AFTER MURALI.

SELECT FNAME, DOJ FROM EMP WHERE DOJ>
(SELECT DOJ FROM EMP WHERE FNAME='MURALI');

148. WAQTD THE DETAILS OF EMP WHO IS WORKING AS SALESMAN AND GETTING SALARY MORE THAN DHARANI.

SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>
(SELECT SAL FROM EMP WHERE FNAME='DHARANI');

149. WAQTD THE EMP FNAME, JOB, SAL IF THE EMP IS GETTING SALARY MORE THAN PRIYA SALARY BUT LESS THAN RAHUL'S SALARY.

SELECT FNAME, JOB, SAL FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='PRIYA') AND SAL<
(SELECT SAL FROM EMP WHERE FNAME='RAHUL');

150. WAQTD THE DETAILS OF EMP WHO WERE BORN AFTER PRIYA.

SELECT * FROM EMP WHERE DOB>
(SELECT DOB FROM EMP WHERE FNAME='PRIYA');

151. WAQTD THE EMP FNAME, DOJ IF THE EMP WAS JOINED 2 YEARS AFTER SAMEER'S JOINING.

SELECT FNAME, DOJ FROM EMP WHERE DOJ>
(SELECT DATE_ADD(DOJ,INTERVAL 2 YEAR) FROM EMP WHERE FNAME='SAMEER');

152. WAQTD THE DETAILS OF EMP IF THE EMP IS 3 YEARS OR MORE YOUNGER THAN SAMEER.

SELECT * FROM EMP WHERE DOB>=
(SELECT DATE_ADD(DOB,INTERVAL 3 YEAR) FROM EMP WHERE FNAME='SAMEER');

153. WAQTD THE EMP FNAME, DOB IF THE EMP IS 2 YEAR OR MORE ELDER THAN FARIYA.

SELECT FNAME, DOB FROM EMP WHERE DOB<
(SELECT DATE_SUB(DOB,INTERVAL 2 YEAR) FROM EMP WHERE FNAME='FARIYA');

154. WAQTD THE DETAILS OF EMP IF THE EMP WAS NOT WORKING IN SAME DEPT AS RAHUL'S DEPT BUT GETTING SALARY MORE THAN DHARANI.

SELECT * FROM EMP WHERE DNO!=
(SELECT DNO FROM EMP WHERE FNAME='RAHUL') AND SAL>
(SELECT SAL FROM EMP WHERE FNAME='DHARANI');
 
155. WAQTD THE DEPT NAME OF AMAN.

SELECT DNAME FROM DEPT WHERE DNO=
(SELECT DNO FROM EMP WHERE FNAME='AMAN');

156. WAQTD THE DEPT NAME OF SAMEER.

SELECT DNAME FROM DEPT WHERE DNO=
(SELECT DNO FROM EMP WHERE FNAME='SAMEER');

157. WAQTD THE DETAILS OF CUSTOMER WHO LIVES IN KORAMANGALA.

SELECT * FROM CUSTOMER WHERE LID=
(SELECT LID FROM LOCATION WHERE LOCATION='KORAMANGALA');

158. WAQTD THE DETAILS OF EMP WHO WORKS IN IT DEPT.

SELECT * FROM EMP WHERE DNO=
(SELECT DNO FROM DEPT WHERE DNAME='IT');

159. WAQTD THE DETAILS OF EMP WHO WORKS IN SALES DEPT OR IT DEPT.

SELECT * FROM EMP WHERE DNO IN
(SELECT DNO FROM DEPT WHERE DNAME IN ('IT','SALES'));

160. WAQTD THE DEPT NAME IF THE DEPT IS LOCATED IN BANGALORE CITY.

SELECT DNAME FROM DEPT WHERE LID IN
(SELECT LID FROM LOCATION WHERE CITY='BANGALORE');

161. WAQTD THE DETAILS OF CUSTOMER WHO LIVES IN CHENNAI.

SELECT * FROM CUSTOMER WHERE LID IN
(SELECT LID FROM LOCATION WHERE CITY='CHENNAI');

162. WAQTD THE LOCATION DETAILS OF THE CUSTOMER WHOSE FIRST NAME IS MEERA.

SELECT * FROM LOCATION WHERE LID IN
(SELECT LID FROM CUSTOMER WHERE FIRST_NAME='MEERA');

163. WAQTD THE DETAILS OF CUSTOMER WHO HAVE ORDERED ANY PRODUCT.
{If a customer has ordered any product, his CID will be present in ORDERS table}

SELECT * FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS);

164. WAQTD THE DETAILS OF PRODUCT WHICH IS UNSOLD.
{If a product has not been ordered even once, then its PRODUCT_ID will not be present in ORDERS table}

SELECT * FROM PRODUCT WHERE PRODUCT_ID NOT IN
(SELECT PRODUCT_ID FROM ORDERS);

165. WAQTD THE DETAILS OF EMP WHO HAVE DELIVERED THE PRODUCTS.
{If any emp has delivered the product, then his eid must be present in ORDERS table}

SELECT * FROM EMP WHERE EID IN
(SELECT EID FROM ORDERS);

166. WAQTD THE DETAILS OF CUSTOMER WHO HAVE ORDERED SMARTPHONE.

SELECT * FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM PRODUCT WHERE PNAME='SMARTPHONE'));

167. WAQTD THE EMP FNAME, JOB, SAL IF THE EMP IS WORKING IN BANGALORE.

SELECT FNAME, JOB, SAL FROM EMP WHERE DNO IN
(SELECT DNO FROM DEPT WHERE LID IN
(SELECT LID FROM LOCATION WHERE CITY='BANGALORE'));

168. WAQTD THE DETAILS OF EMP WHO DELIVERED HEADPHONES.

SELECT * FROM EMP WHERE EID IN
(SELECT EID FROM ORDERS WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM PRODUCT WHERE PNAME='HEADPHONES'));

169. WAQTD THE DEPT NAME IF THE EMP IS GETTING SALARY MORE THAN FARIYA.

SELECT DNAME FROM DEPT WHERE DNO IN
(SELECT DNO FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='FARIYA'));

170. WAQTD THE DETAILS OF PRODUCTS ORDERED BY A CUSTOMER WHOSE FNAME IS KIRAN.

SELECT * FROM PRODUCT WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM ORDERS WHERE CID IN
(SELECT CID FROM CUSTOMER WHERE FIRST_NAME='KIRAN'));

171. WAQTD THE WORKING LOCATION DETAILS OF EMP WHO WORKS AS SALESMAN.

SELECT * FROM LOCATION WHERE LID IN
(SELECT LID FROM DEPT WHERE DNO IN
(SELECT DNO FROM EMP WHERE JOB='SALESMAN'));

172. WAQTD THE DETAILS OF PRODUCTS ORDERED FROM CHENNAI.
{Location -> Customer -> Orders -> Product}

SELECT * FROM PRODUCT WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM ORDERS WHERE CID IN
(SELECT CID FROM CUSTOMER WHERE LID IN
(SELECT LID FROM LOCATION WHERE CITY='CHENNAI')));

173. WAQTD THE DETAILS OF EMP WHO DELIVERED THE PRODUCT TO MYSORE.

SELECT * FROM EMP WHERE EID IN
(SELECT EID FROM ORDERS WHERE CID IN
(SELECT CID FROM CUSTOMER WHERE LID IN
(SELECT LID FROM LOCATION WHERE CITY='MYSORE')));

174. WAQTD THE LOCATION DETAILS DELIVERED BY JAHNAVI.

SELECT * FROM LOCATION WHERE LID IN
(SELECT LID FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS WHERE EID IN
(SELECT EID FROM EMP WHERE FNAME='JAHNAVI')));

175. WAQTD THE NUMBER OF ORDERS DELIVERED BY EACH EMPS.

SELECT COUNT(*),EID
FROM ORDERS
GROUP BY EID;

176. WAQTD THE DETAILS OF EMP WHO IS GETTING SALARY MORE THAN RAHUL.

SELECT * FROM EMP WHERE SAL>
(SELECT SAL FROM EMP WHERE FNAME='RAHUL');

177. WAQTD THE DETAILS OF EMP WHO IS GETTING SALARY MORE THAN ALL THE SALESMAN.

SELECT * FROM EMP WHERE SAL>ALL
(SELECT SAL FROM EMP WHERE JOB='SALESMAN');

 178. WAQTD THE LOCATION DETAILS DELIVERED BY JAHNAVI.

SELECT * FROM LOCATION WHERE LID IN
(SELECT LID FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS WHERE EID IN
(SELECT EID FROM EMP WHERE FNAME='JAHNAVI')));

 179. WAQTD THE DETAILS OF EMP WHO ARE GETTING SALARY LESS THAN PRIYA.

 SELECT * FROM EMP WHERE SAL <
(SELECT SAL FROM EMP WHERE FNAME='PRIYA');

 180. WAQTD THE DETAILS OF CUSTOMER WHO HAVE ORDERED LAPTOP.

 SELECT * FROM CUSTOMER WHERE CID IN
(SELECT CID FROM ORDERS WHERE PRODUCT_ID IN
(SELECT PRODUCT_ID FROM PRODUCT WHERE PNAME='LAPTOP'));

 181. WAQTD THE DETAILS OF EMP WHO WORKS IN THE SAME DEPT AS KIRAN.
 SELECT * FROM EMP WHERE DNO =
(SELECT DNO FROM EMP WHERE FNAME='KIRAN');





