11. WAQTD THE EMP FNAME, JOB ROLE IF THE EMP IS WORKING AS SALESMAN.

SELECT FNAME,JOB
FROM EMP
WHERE JOB='SALESMAN';

12. WAQTD THE EMP FNAME, SAL, JOB IF THE EMP IS GETTING SALARY MORE THAN 50000.

SELECT FNAME,SAL,JOB
FROM EMP
WHERE SAL>50000;

13. WAQTD THE EMP FNAME, DOB IF THE EMP WAS BORN AFTER 1995.

SELECT FNAME,DOB
FROM EMP
WHERE DOB>'1995-12-31';

14. WAQTD THE EMP FNAME, DOJ IF THE EMP WAS HIRED BEFORE 2020.

SELECT FNAME,DOJ
FROM EMP
WHERE DOJ<'2020-01-01';

15. WAQTD THE DETAILS OF EMP WHO ARE NOT WORKING AS MANAGER.

SELECT *
FROM EMP
WHERE JOB!='MANAGER';

16. WAQTD THE DETAILS OF EMP WHO ARE WORKING AS SALESMAN

SELECT * 
FROM EMP
WHERE JOB = 'SALESMAN';

17. WAQTD THE DETAILS OF EMP WHO ARE NOT WORKING AS DISPATCHER

SELECT *
FROM EMP
WHERE JOB != "DISPATCHER";

18. WAQTD THE FNAME,DOB,JOB OF EMP WHO ARE BORN IN 1997
SELECT FNAME,DOB,JOB
FROM EMP
WHERE DOB=YEAR("1997");

19. WAQTD THE EMP FNAME, SAL, JOB OF EMP WHO ARE GETTING A SALARY LESS THAN 30000.
SELECT FNAME, SAL, JOB
FROM EMP
WHERE SAL < 30000;


